title: SMB3 Romhacks
email: narfman0@gmail.com
description: >-
  SMB3 Romhacks is a read only replica of src data
baseurl: "/smb3-romhacks"
url: "https://narfman0.github.io"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
header_pages:
  - pages/links.md